insert into public.size_options (id,label,dimensions,price_modifier,sort_order) values
('size-s','8 × 12 in (A4)','21 × 30 cm',0,0),
('size-m','12 × 18 in (A3)','30 × 42 cm',350,1),
('size-l','18 × 24 in (A2)','42 × 60 cm',750,2),
('size-xl','24 × 36 in (A1)','60 × 90 cm',1350,3) on conflict (id) do nothing;
insert into public.frame_options (id,name,color_code,price_modifier,sort_order) values
('unframed','Poster Only (No Frame)','#F4EFE6',0,0),
('black_wood','Matte Black Aluminum','#1A1A1A',400,1),
('gold_champagne','Champagne Brushed Gold','#C5A059',600,2),
('natural_oak','Scandinavian Natural Oak','#C8A87D',450,3),
('classic_white','Studio Pure White','#FFFFFF',400,4) on conflict (id) do nothing;
insert into public.categories (name,slug,description,image_url,sort_order) values
('Posters','posters','High-definition 300 GSM matte art paper prints with rich pigment inks.','https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=800&q=80',0),
('Framed Posters','framed-posters','Ready-to-hang gallery grade frames with shatterproof acrylic glass.','https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=800&q=80',1),
('Wall Art','wall-art','Statement centerpieces crafted to transform bare walls into galleries.','https://images.unsplash.com/photo-1582561424760-0321d75e81fa?auto=format&fit=crop&w=800&q=80',2),
('Minimal Art','minimal-art','Understated line work, neutral geometric silhouettes, and organic forms.','https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=800&q=80',3),
('Abstract Art','abstract-art','Bold textures, fluid acrylic motions, and contemporary color fields.','https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=800&q=80',4),
('Islamic Art','islamic-art','Exquisite modern Arabic calligraphy and sacred geometric compositions.','https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=800&q=80',5),
('Quote Art','quote-art','Inspiring typography, philosophy, and mindful words in refined serif style.','https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80',6),
('Aesthetic Art','aesthetic-art','Gen-Z aesthetic, warm terracotta, sun motifs, and serene botanical sketches.','https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',7),
('Nature & Landscape','nature-landscape','Misty pine forests, desert dunes, serene oceans, and mountain horizons.','https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',8),
('Living Room Décor','living-room-decor','Curated large-scale triptychs and focal points for entertaining spaces.','https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',9),
('Bedroom Décor','bedroom-decor','Calming palettes, peaceful abstracts, and cozy mood enhancers.','https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=800&q=80',10),
('Office Décor','office-decor','Focus-boosting architecture, monochrome geometry, and vision boards.','https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80',11),
('New Arrivals','new-arrivals','Fresh contemporary drops designed by independent studio artists.','https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=800&q=80',12),
('Best Sellers','best-sellers','The most coveted prints gracing thousands of aesthetic homes.','https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=800&q=80',13) on conflict (name) do nothing;
insert into public.products (name,slug,tagline,description,base_price,compare_at_price,sku,orientation,theme,style,color_palette,tags,materials,paper_gsm,frame_material,care_instructions,shipping_time,rating,review_count,stock_quantity,is_featured,is_best_seller,is_new_arrival,seo_title,seo_description) values ('Solitude Horizon — Minimal Sun & Dunes','solitude-horizon-minimal-sun-dunes','Warm terracotta landscape with geometric sun & flock of birds in flight','Solitude Horizon embodies serene minimalism. Featuring the signature FRAME CART aesthetic — a warm golden sun casting a gentle glow over layered matte black and dune taupe mountain ridges, accompanied by soaring birds. Printed on museum-heritage 300 GSM cotton rag paper that brings deep optical contrast into your living space.',599,1199,'FC-SOLITUDE-HORIZON-MIN','portrait','Minimalist Landscape','Modern Scandinavian','["#FAF6EE","#1A1A1A","#C5A059","#A89F91"]'::jsonb,'["minimal","sun","mountains","gold","neutral","living room"]'::jsonb,'300 GSM Heavyweight Matte Canvas Paper with 12-Color Pigment Archival Ink.','300 GSM Premium Archival Paper','Extruded lightweight anodized aluminum or solid kiln-dried pine wood with 2mm anti-glare shatterproof acrylic glass.','Dust lightly with a dry microfiber cloth. Avoid direct long exposure to harsh moisture.','Dispatched in 24-48 hours. Delivered in 3-5 business days pan-India.',4.9,148,42,true,true,false,'Solitude Horizon — Minimal Sun & Dunes | FRAME CART','Warm terracotta landscape with geometric sun & flock of birds in flight') on conflict (slug) do nothing;
insert into public.product_images (product_id,url,kind,sort_order) select p.id, v.url, v.kind, v.ord from public.products p, (values ('https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1000&q=85','gallery',0),('https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=1000&q=85','gallery',1),('https://images.unsplash.com/photo-1582561424760-0321d75e81fa?auto=format&fit=crop&w=1000&q=85','gallery',2),('https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=85','lifestyle',3),('https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=1200&q=85','lifestyle',4)) as v(url,kind,ord) where p.slug = 'solitude-horizon-minimal-sun-dunes';
insert into public.product_categories (product_id,category_id) select p.id, c.id from public.products p, public.categories c where p.slug='solitude-horizon-minimal-sun-dunes' and c.name in ('Minimal Art','Framed Posters','Aesthetic Art','Living Room Décor','Best Sellers') on conflict do nothing;
insert into public.products (name,slug,tagline,description,base_price,compare_at_price,sku,orientation,theme,style,color_palette,tags,materials,paper_gsm,frame_material,care_instructions,shipping_time,rating,review_count,stock_quantity,is_featured,is_best_seller,is_new_arrival,seo_title,seo_description) values ('Ayat al-Kursi — Golden Modern Calligraphy','ayat-al-kursi-golden-modern-calligraphy','Timeless Islamic verse composed in sleek champagne gold & deep noir contrast','A breathtaking contemporary tribute to the Throne Verse (Ayat al-Kursi). Scripted in fluid modern Thuluth Arabic calligraphy adorned with shimmering champagne gold foil accents against a velvety matte noir canvas. Perfect as a sacred centerpiece for spiritual warmth and elegance in your home.',799,1599,'FC-AYAT-AL-KURSI-GOLDEN','portrait','Spiritual & Calligraphy','Modern Islamic','["#141414","#C5A059","#FAF7F2"]'::jsonb,'["islamic","calligraphy","ayatul kursi","gold","black","sacred"]'::jsonb,'High density museum cotton rag with gold foil metallic thermal infusion.','320 GSM Archival Velvet Paper','Luxury Champagne Brushed Gold Metal Frame with tempered organic glass.','Wipe with soft cotton cloth. Ready-to-hang pre-installed sawtooth brass bracket.','Dispatched in 24-48 hours. Delivered in 3-5 business days pan-India.',5,210,28,true,true,false,'Ayat al-Kursi — Golden Modern Calligraphy | FRAME CART','Timeless Islamic verse composed in sleek champagne gold & deep noir contrast') on conflict (slug) do nothing;
insert into public.product_images (product_id,url,kind,sort_order) select p.id, v.url, v.kind, v.ord from public.products p, (values ('https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1000&q=85','gallery',0),('https://images.unsplash.com/photo-1582561424760-0321d75e81fa?auto=format&fit=crop&w=1000&q=85','gallery',1),('https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1200&q=85','lifestyle',2)) as v(url,kind,ord) where p.slug = 'ayat-al-kursi-golden-modern-calligraphy';
insert into public.product_categories (product_id,category_id) select p.id, c.id from public.products p, public.categories c where p.slug='ayat-al-kursi-golden-modern-calligraphy' and c.name in ('Islamic Art','Wall Art','Living Room Décor','Best Sellers','Framed Posters') on conflict do nothing;
insert into public.products (name,slug,tagline,description,base_price,compare_at_price,sku,orientation,theme,style,color_palette,tags,materials,paper_gsm,frame_material,care_instructions,shipping_time,rating,review_count,stock_quantity,is_featured,is_best_seller,is_new_arrival,seo_title,seo_description) values ('Serene Botanical Curve No. 04','serene-botanical-curve-no-04','Earthy beige and olive fluid botanical contour silhouette','Inspired by Japanese Ikebana simplicity and Mediterranean warmth. Subtle contour lines celebrate organic leaf bends against a textured plaster cream background. Pairs seamlessly with modern wooden furniture, beige linen curtains, and warm lamp lighting.',499,999,'FC-SERENE-BOTANICAL-CUR','portrait','Flora & Fauna','Japandi Minimal','["#FAF7F2","#6B705C","#D4A373","#1A1A1A"]'::jsonb,'["botanical","leaves","minimal","bedroom","japandi"]'::jsonb,'Fine-grain matte museum paper with non-reflective UV finish.','280 GSM Matte Paper','Scandinavian Natural Oak Frame with seamless corner joints.','Indoor display only. Clean acrylic with dry lens cloth.','Dispatched in 24-48 hours. Delivered in 3-5 business days pan-India.',4.8,84,35,true,false,true,'Serene Botanical Curve No. 04 | FRAME CART','Earthy beige and olive fluid botanical contour silhouette') on conflict (slug) do nothing;
insert into public.product_images (product_id,url,kind,sort_order) select p.id, v.url, v.kind, v.ord from public.products p, (values ('https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1000&q=85','gallery',0),('https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=1000&q=85','gallery',1),('https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=1200&q=85','lifestyle',2)) as v(url,kind,ord) where p.slug = 'serene-botanical-curve-no-04';
insert into public.product_categories (product_id,category_id) select p.id, c.id from public.products p, public.categories c where p.slug='serene-botanical-curve-no-04' and c.name in ('Posters','Minimal Art','Bedroom Décor','Aesthetic Art') on conflict do nothing;
insert into public.products (name,slug,tagline,description,base_price,compare_at_price,sku,orientation,theme,style,color_palette,tags,materials,paper_gsm,frame_material,care_instructions,shipping_time,rating,review_count,stock_quantity,is_featured,is_best_seller,is_new_arrival,seo_title,seo_description) values ('Kyoto Mist & Pagoda Silhouette','kyoto-mist-pagoda-silhouette','Atmospheric monochrome Japanese architecture shrouded in morning fog','A contemplative fine-art photograph of ancient Kyoto temple roofs emerging through dense mountain fog. The dramatic tonal range between deep ink blacks and mist whites creates a peaceful sanctuary atmosphere in your study or bedroom.',649,1299,'FC-KYOTO-MIST-PAGODA-SI','landscape','Architecture & Fog','Monochrome Editorial','["#1A1A1A","#8D99AE","#EDF2F4","#2B2D42"]'::jsonb,'["kyoto","japan","fog","monochrome","office","landscape"]'::jsonb,'High contrast black and white giclée print with deep d-max saturation.','310 GSM Fine Art Pearl','Matte Black Aluminum Frame with white conservation mat board.','Do not use chemical glass sprays.','Dispatched in 24-48 hours. Delivered in 3-5 business days pan-India.',4.9,97,19,false,true,false,'Kyoto Mist & Pagoda Silhouette | FRAME CART','Atmospheric monochrome Japanese architecture shrouded in morning fog') on conflict (slug) do nothing;
insert into public.product_images (product_id,url,kind,sort_order) select p.id, v.url, v.kind, v.ord from public.products p, (values ('https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=85','gallery',0),('https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=1000&q=85','gallery',1),('https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=85','lifestyle',2)) as v(url,kind,ord) where p.slug = 'kyoto-mist-pagoda-silhouette';
insert into public.product_categories (product_id,category_id) select p.id, c.id from public.products p, public.categories c where p.slug='kyoto-mist-pagoda-silhouette' and c.name in ('Nature & Landscape','Wall Art','Office Décor','Posters') on conflict do nothing;
insert into public.products (name,slug,tagline,description,base_price,compare_at_price,sku,orientation,theme,style,color_palette,tags,materials,paper_gsm,frame_material,care_instructions,shipping_time,rating,review_count,stock_quantity,is_featured,is_best_seller,is_new_arrival,seo_title,seo_description) values ('Manifest Your Reality — Editorial Typography','manifest-your-reality-editorial-typography','Bold aesthetic typography poster with subtle retro grain and modern wisdom','A daily visual anchor designed for creators, entrepreneurs, and dreamers. Clean editorial serif typography paired with minimal geometric accent markings. Perfect for styling modern work desks, home offices, and creative studio walls.',549,1099,'FC-MANIFEST-YOUR-REALIT','portrait','Inspiration & Mindset','Typography & Editorial','["#FAF7F2","#141414","#C5A059"]'::jsonb,'["quote","typography","office","manifest","motivation","minimal"]'::jsonb,'Warm off-white archival paper with crisp high-density letterpress fidelity.','300 GSM Heavyweight Matte','Matte Black or Studio White Aluminum Frame.','Wipe frame edges gently with a clean dry microfiber cloth.','Dispatched in 24-48 hours. Delivered in 3-5 business days pan-India.',4.7,62,50,true,false,true,'Manifest Your Reality — Editorial Typography | FRAME CART','Bold aesthetic typography poster with subtle retro grain and modern wisdom') on conflict (slug) do nothing;
insert into public.product_images (product_id,url,kind,sort_order) select p.id, v.url, v.kind, v.ord from public.products p, (values ('https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=1000&q=85','gallery',0),('https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1000&q=85','gallery',1),('https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=85','lifestyle',2)) as v(url,kind,ord) where p.slug = 'manifest-your-reality-editorial-typography';
insert into public.product_categories (product_id,category_id) select p.id, c.id from public.products p, public.categories c where p.slug='manifest-your-reality-editorial-typography' and c.name in ('Quote Art','Office Décor','Aesthetic Art','New Arrivals') on conflict do nothing;
insert into public.products (name,slug,tagline,description,base_price,compare_at_price,sku,orientation,theme,style,color_palette,tags,materials,paper_gsm,frame_material,care_instructions,shipping_time,rating,review_count,stock_quantity,is_featured,is_best_seller,is_new_arrival,seo_title,seo_description) values ('Fluid Aureolin — Modern Textured Abstract','fluid-aureolin-modern-textured-abstract','Sculptural beige plaster waves with shimmering molten gold leaf streams','Fluid Aureolin captures tactile sculptural luxury. Evoking layers of Mediterranean lime plaster and molten gold flows that catch sunlight differently throughout the day. It creates an undeniable conversation piece in grand living spaces.',849,1699,'FC-FLUID-AUREOLIN-MODER','square','Organic Fluidity','Contemporary Textured','["#FAF5EB","#C5A059","#7D6B58","#1A1A1A"]'::jsonb,'["abstract","gold leaf","textured","living room","luxury","plaster"]'::jsonb,'Archival Giclée canvas textured print with metallic gold leaf finish.','340 GSM Canvas Texture Paper','Champagne Brushed Gold Solid Floating Frame.','Hang securely using included heavy-duty wall anchors.','Dispatched in 24-48 hours. Delivered in 3-5 business days pan-India.',5,175,15,true,true,false,'Fluid Aureolin — Modern Textured Abstract | FRAME CART','Sculptural beige plaster waves with shimmering molten gold leaf streams') on conflict (slug) do nothing;
insert into public.product_images (product_id,url,kind,sort_order) select p.id, v.url, v.kind, v.ord from public.products p, (values ('https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1000&q=85','gallery',0),('https://images.unsplash.com/photo-1582561424760-0321d75e81fa?auto=format&fit=crop&w=1000&q=85','gallery',1),('https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=85','lifestyle',2)) as v(url,kind,ord) where p.slug = 'fluid-aureolin-modern-textured-abstract';
insert into public.product_categories (product_id,category_id) select p.id, c.id from public.products p, public.categories c where p.slug='fluid-aureolin-modern-textured-abstract' and c.name in ('Abstract Art','Wall Art','Living Room Décor','Framed Posters','Best Sellers') on conflict do nothing;
insert into public.products (name,slug,tagline,description,base_price,compare_at_price,sku,orientation,theme,style,color_palette,tags,materials,paper_gsm,frame_material,care_instructions,shipping_time,rating,review_count,stock_quantity,is_featured,is_best_seller,is_new_arrival,seo_title,seo_description) values ('Bismillah Calligraphy — Minimal Crescent','bismillah-calligraphy-minimal-crescent','Graceful Islamic phrase enclosed in a fine golden circular emblem','An understated spiritual masterpiece. The sacred phrase "Bismillah al-Rahman al-Rahim" flows inside a subtle celestial ring. Designed to bring peaceful blessings, calm reassurance, and refined luxury into entryways, hallways, and living rooms.',699,1399,'FC-BISMILLAH-CALLIGRAPH','square','Calligraphy & Sacred Geometry','Modern Minimalist','["#FAF6EE","#C5A059","#1A1A1A"]'::jsonb,'["islamic","bismillah","arabic","gold","minimal","entryway"]'::jsonb,'Ultra-smooth museum matte paper with 100% acid-free base.','300 GSM Archival Card','Champagne Gold or Matte Black Frame with 2mm Acrylic Glass.','Keep away from excessive dampness.','Dispatched in 24-48 hours. Delivered in 3-5 business days pan-India.',4.9,112,30,false,false,true,'Bismillah Calligraphy — Minimal Crescent | FRAME CART','Graceful Islamic phrase enclosed in a fine golden circular emblem') on conflict (slug) do nothing;
insert into public.product_images (product_id,url,kind,sort_order) select p.id, v.url, v.kind, v.ord from public.products p, (values ('https://images.unsplash.com/photo-1582561424760-0321d75e81fa?auto=format&fit=crop&w=1000&q=85','gallery',0),('https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1000&q=85','gallery',1),('https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1200&q=85','lifestyle',2)) as v(url,kind,ord) where p.slug = 'bismillah-calligraphy-minimal-crescent';
insert into public.product_categories (product_id,category_id) select p.id, c.id from public.products p, public.categories c where p.slug='bismillah-calligraphy-minimal-crescent' and c.name in ('Islamic Art','Minimal Art','Wall Art','New Arrivals') on conflict do nothing;
insert into public.products (name,slug,tagline,description,base_price,compare_at_price,sku,orientation,theme,style,color_palette,tags,materials,paper_gsm,frame_material,care_instructions,shipping_time,rating,review_count,stock_quantity,is_featured,is_best_seller,is_new_arrival,seo_title,seo_description) values ('Terracotta Geometry & Sun Shadow','terracotta-geometry-sun-shadow','Warm earth tone archways, circles, and architectural shadows','An architectural tribute to mid-century modern shapes and Mediterranean courtyards. Warm terracotta, burnt sienna, and sand hues blend into a balanced geometric harmony that grounds cozy bedrooms and reading corners.',529,1049,'FC-TERRACOTTA-GEOMETRY-','portrait','Architecture & Geometry','Boho Bauhaus','["#D08C5A","#FAF6EE","#3A3A3A","#E0A96D"]'::jsonb,'["terracotta","boho","arches","geometry","bedroom","warm"]'::jsonb,'Warm-toned heavy art stock with velvet texture.','290 GSM Cotton Matte','Scandinavian Natural Oak or Matte Black Frame.','Easy wipe down with clean microfiber.','Dispatched in 24-48 hours. Delivered in 3-5 business days pan-India.',4.8,76,22,false,false,false,'Terracotta Geometry & Sun Shadow | FRAME CART','Warm earth tone archways, circles, and architectural shadows') on conflict (slug) do nothing;
insert into public.product_images (product_id,url,kind,sort_order) select p.id, v.url, v.kind, v.ord from public.products p, (values ('https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=1000&q=85','gallery',0),('https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1000&q=85','gallery',1),('https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=1200&q=85','lifestyle',2)) as v(url,kind,ord) where p.slug = 'terracotta-geometry-sun-shadow';
insert into public.product_categories (product_id,category_id) select p.id, c.id from public.products p, public.categories c where p.slug='terracotta-geometry-sun-shadow' and c.name in ('Aesthetic Art','Bedroom Décor','Posters','Framed Posters') on conflict do nothing;
insert into public.product_variants (product_id,size_id,frame_id,stock_quantity) select p.id, s.id, f.id, greatest(p.stock_quantity,0) from public.products p cross join public.size_options s cross join public.frame_options f on conflict do nothing;
insert into public.coupons (code,discount_type,discount_value,min_order_value,max_discount,description,is_active,per_user_limit) values
('WELCOME10','percentage',10,999,300,'10% off your first order above ₹999',true,1),
('FRAME200','flat',200,1499,null,'Flat ₹200 off on orders above ₹1499',true,3),
('GOLD15','percentage',15,2499,600,'15% off on premium framed orders above ₹2499',true,2) on conflict (code) do nothing;